config = {
    "data_path": "/teamspace/uploads/uaspeechall/data",
    "model_name": "facebook/wav2vec2-large-xls-r-300m",
    "output_dir": "wav2vec2-large-xls-r-300m-dysarthria-big-dataset",
    "batch_size": 16,
    "num_epochs": 30,
    "save_steps": 200,
    "eval_steps": 200,
    "logging_steps": 200,
    "learning_rate": 3e-4,
    "warmup_steps": 500,
    "push_to_hub": True,
    "attention_dropout": 0.0,
    "hidden_dropout": 0.0,
    "feat_proj_dropout": 0.0,
    "mask_time_prob": 0.05,
    "layerdrop": 0.0,
}
